"""episode 001 production: song table, short and scene fields

Revision ID: 29891cfbf82f
Revises: ab044c62bc0e
Create Date: 2026-08-09 15:13:57.070004

Adds the ``songs`` table (one per Episode, enforced by the unique
``episode_id`` FK — the Music stage's written song package: lyrics,
purpose, duration, production notes, Suno-ready style prompt; no
status/approval lifecycle, since nothing in this milestone reviews
lyrics), one nullable column on ``scenes`` (``voice_notes``, for
per-scene emotional tone/pacing/pronunciation direction), and four
nullable columns on ``shorts`` (``spoken_text_ar``, ``on_screen_text_ar``,
``target_duration_seconds``, ``editing_notes`` — a Short's own edit
script, distinct from its source Scenes' full dialogue). All additive
and nullable — existing rows come through unchanged, no backfill
needed. See docs/30_MILESTONE_6_EPISODE_001_PRODUCTION_STATUS.md.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29891cfbf82f'
down_revision: Union[str, None] = 'ab044c62bc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('lyrics_ar', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('production_notes', sa.Text(), nullable=True),
    sa.Column('suno_style_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoken_text_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('on_screen_text_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('editing_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_column('editing_notes')
        batch_op.drop_column('target_duration_seconds')
        batch_op.drop_column('on_screen_text_ar')
        batch_op.drop_column('spoken_text_ar')

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('voice_notes')

    op.drop_table('songs')
    # ### end Alembic commands ###
