"""initial schema

Revision ID: 37154bea36d1
Revises: 
Create Date: 2026-08-01 23:18:23.086106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37154bea36d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_records',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='approvaldecision', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index('ix_approval_records_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('characters',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('episodes',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.String(length=256), nullable=False),
    sa.Column('title_en', sa.String(length=256), nullable=False),
    sa.Column('lesson', sa.String(length=256), nullable=False),
    sa.Column('logline_ar', sa.Text(), nullable=True),
    sa.Column('dialogue_language', sa.String(length=64), nullable=False),
    sa.Column('runtime_target_minutes_min', sa.Integer(), nullable=False),
    sa.Column('runtime_target_minutes_max', sa.Integer(), nullable=False),
    sa.Column('includes_song', sa.Boolean(), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('IDEA', 'LESSON', 'OUTLINE', 'SCRIPT', 'STORYBOARD', 'IMAGE_PROMPTS', 'VIDEO_PROMPTS', 'VOICE', 'SONG', 'EDITING', 'THUMBNAIL', 'SEO', 'READY_TO_PUBLISH', 'PUBLISHED', name='pipelinestage', native_enum=False, length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('character_versions',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=16), nullable=False),
    sa.Column('outfit_version', sa.String(length=16), nullable=True),
    sa.Column('description_of_change', sa.Text(), nullable=True),
    sa.Column('visual_summary', sa.Text(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=False),
    sa.Column('allowed_accessories', sa.JSON(), nullable=False),
    sa.Column('relative_height', sa.String(length=64), nullable=True),
    sa.Column('master_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED_CANON', 'ARCHIVED', name='characterversionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'version_number', name='uq_character_version_number')
    )
    op.create_table('episode_characters',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'character_id')
    )
    op.create_table('production_tasks',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', name='productiontaskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dialogue_ar', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'order_index', name='uq_scene_order_per_episode')
    )
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('prompt_type', sa.Enum('IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'TEXT', name='prompttype', native_enum=False, length=32), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('target_tool', sa.String(length=128), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    op.create_table('scene_characters',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'character_id')
    )
    op.create_table('assets',
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'THUMBNAIL', 'DOCUMENT', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('source_tool', sa.String(length=128), nullable=True),
    sa.Column('license_status', sa.String(length=128), nullable=True),
    sa.Column('commercial_use_status', sa.String(length=64), nullable=True),
    sa.Column('prompt_used_id', sa.Uuid(), nullable=True),
    sa.Column('character_version_id', sa.Uuid(), nullable=True),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('approval_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_used_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum', name='uq_asset_checksum'),
    sa.UniqueConstraint('relative_path', name='uq_asset_relative_path')
    )
    op.create_table('character_references',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('character_version_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_current_canon', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('license_records',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('license_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('terms_summary', sa.Text(), nullable=True),
    sa.Column('commercial_use_allowed', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shorts',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('short_index', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.String(length=256), nullable=True),
    sa.Column('source_timestamp_range', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'EDITED', 'EXPORTED', 'PUBLISHED', name='shortstatus', native_enum=False, length=32), nullable=False),
    sa.Column('export_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['export_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'short_index', name='uq_short_index_per_episode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorts')
    op.drop_table('license_records')
    op.drop_table('character_references')
    op.drop_table('assets')
    op.drop_table('scene_characters')
    op.drop_table('prompt_templates')
    op.drop_table('scenes')
    op.drop_table('production_tasks')
    op.drop_table('episode_characters')
    op.drop_table('character_versions')
    op.drop_table('episodes')
    op.drop_table('characters')
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_records_entity')

    op.drop_table('approval_records')
    # ### end Alembic commands ###
