"""milestone 7 generation jobs

Revision ID: 70415d0caa93
Revises: 29891cfbf82f
Create Date: 2026-08-09 16:55:49.137289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70415d0caa93'
down_revision: Union[str, None] = '29891cfbf82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('workflow_name', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCEL_REQUESTED', 'CANCELLED', name='generationjobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('negative_prompt_text', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('character_version_id', sa.Uuid(), nullable=True),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('short_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_asset_id', sa.Uuid(), nullable=True),
    sa.Column('retry_of_job_id', sa.Uuid(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL', name='fk_generation_jobs_character_id_characters'),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], ondelete='SET NULL', name='fk_generation_jobs_character_version_id_character_versions'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL', name='fk_generation_jobs_episode_id_episodes'),
    sa.ForeignKeyConstraint(['result_asset_id'], ['assets.id'], ondelete='SET NULL', name='fk_generation_jobs_result_asset_id_assets'),
    sa.ForeignKeyConstraint(['retry_of_job_id'], ['generation_jobs.id'], ondelete='SET NULL', name='fk_generation_jobs_retry_of_job_id_generation_jobs'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL', name='fk_generation_jobs_scene_id_scenes'),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='SET NULL', name='fk_generation_jobs_short_id_shorts'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_generation_jobs_batch_id', ['batch_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_job_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_assets_generation_job_id_generation_jobs',
            'generation_jobs',
            ['generation_job_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_generation_job_id_generation_jobs', type_='foreignkey')
        batch_op.drop_column('generation_job_id')

    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_jobs_batch_id')

    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
