"""scene estimated duration

Revision ID: 8ed8cbd56eee
Revises: 98db36ba39d7
Create Date: 2026-08-01 23:56:52.517672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed8cbd56eee'
down_revision: Union[str, None] = '98db36ba39d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('estimated_duration_seconds')

    # ### end Alembic commands ###
