"""milestone 3 schema additions

Revision ID: 98db36ba39d7
Revises: 37154bea36d1
Create Date: 2026-08-01 23:45:07.191447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98db36ba39d7'
down_revision: Union[str, None] = '37154bea36d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_scenes',
    sa.Column('short_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['short_id'], ['shorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('short_id', 'scene_id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('scene_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('short_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_assets_short_id_shorts', 'shorts', ['short_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_assets_scene_id_scenes', 'scenes', ['scene_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('active_version_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_characters_active_version_id_character_versions',
            'character_versions',
            ['active_version_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hashtags', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('credits_text', sa.Text(), nullable=True))

    with op.batch_alter_table('license_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_relative_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('attribution_required', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('attribution_text', sa.Text(), nullable=True))

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('STORY', 'STORYBOARD', 'CHARACTER', 'BACKGROUND', 'IMAGE', 'VIDEO', 'VOICE', 'SONG', 'THUMBNAIL', 'SEO', 'PUBLISHING', name='promptcategory', native_enum=False, length=32), server_default='STORY', nullable=False))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_title_en', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('hook_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('caption_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hashtags', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shorts', schema=None) as batch_op:
        batch_op.drop_column('hashtags')
        batch_op.drop_column('caption_ar')
        batch_op.drop_column('hook_ar')
        batch_op.drop_column('working_title_en')

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('category')

    with op.batch_alter_table('license_records', schema=None) as batch_op:
        batch_op.drop_column('attribution_text')
        batch_op.drop_column('attribution_required')
        batch_op.drop_column('proof_relative_path')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_column('credits_text')
        batch_op.drop_column('hashtags')
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_ar')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_characters_active_version_id_character_versions', type_='foreignkey'
        )
        batch_op.drop_column('active_version_id')
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_scene_id_scenes', type_='foreignkey')
        batch_op.drop_constraint('fk_assets_short_id_shorts', type_='foreignkey')
        batch_op.drop_column('short_id')
        batch_op.drop_column('scene_id')
        batch_op.drop_column('role')

    op.drop_table('short_scenes')
    # ### end Alembic commands ###
