"""episode workspace script and scene fields

Revision ID: ab044c62bc0e
Revises: 1017c6c7ae38
Create Date: 2026-08-08 22:49:49.794369

Adds the ``scripts`` table (one per Episode, enforced by the unique
``episode_id`` FK) and four nullable columns on ``scenes``
(``title``, ``camera_direction``, ``prompt_text``,
``negative_prompt_text``) for the Episode Workspace milestone. All
additive and nullable — existing Scene rows come through unchanged, no
backfill needed. See docs/29_EPISODE_WORKSPACE_STATUS.md.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab044c62bc0e'
down_revision: Union[str, None] = '1017c6c7ae38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_script', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'APPROVED', name='scriptstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('camera_direction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prompt_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('negative_prompt_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('negative_prompt_text')
        batch_op.drop_column('prompt_text')
        batch_op.drop_column('camera_direction')
        batch_op.drop_column('title')

    op.drop_table('scripts')
    # ### end Alembic commands ###
