"""milestone 9 voice production

Revision ID: c44fa72978d9
Revises: 70415d0caa93
Create Date: 2026-08-12 13:48:13.503345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44fa72978d9'
down_revision: Union[str, None] = '70415d0caa93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_overrides',
    sa.Column('term', sa.String(length=128), nullable=False),
    sa.Column('replacement', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', name='uq_pronunciation_override_term')
    )
    op.create_table('voice_profiles',
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_key', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=128), nullable=False),
    sa.Column('provider_model', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('dialect_style', sa.String(length=64), nullable=True),
    sa.Column('voice_direction', sa.Text(), nullable=True),
    sa.Column('default_parameters', sa.JSON(), nullable=False),
    sa.Column('sample_asset_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogue_lines',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('speaker_raw', sa.String(length=128), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_key', sa.String(length=64), nullable=True),
    sa.Column('authored_text', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialogue_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialogue_lines_scene_id'), ['scene_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialogue_line_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Float(), nullable=True))
        batch_op.create_foreign_key(
            'fk_assets_dialogue_line_id_dialogue_lines',
            'dialogue_lines',
            ['dialogue_line_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialogue_line_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_generation_jobs_dialogue_line_id'), ['dialogue_line_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_generation_jobs_dialogue_line_id_dialogue_lines',
            'dialogue_lines',
            ['dialogue_line_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_generation_jobs_dialogue_line_id_dialogue_lines', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_dialogue_line_id'))
        batch_op.drop_column('dialogue_line_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_dialogue_line_id_dialogue_lines', type_='foreignkey')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('dialogue_line_id')

    with op.batch_alter_table('dialogue_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialogue_lines_scene_id'))

    op.drop_table('dialogue_lines')
    op.drop_table('voice_profiles')
    op.drop_table('pronunciation_overrides')
    # ### end Alembic commands ###
