"""dialogue_line reviewed_tts_text

Revision ID: cfe72eef4ffa
Revises: f5d8ae4a66d8
Create Date: 2026-08-15 16:04:37.938729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe72eef4ffa'
down_revision: Union[str, None] = 'f5d8ae4a66d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogue_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_tts_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogue_lines', schema=None) as batch_op:
        batch_op.drop_column('reviewed_tts_text')

    # ### end Alembic commands ###
