"""scene is_song_scene flag

Revision ID: f5d8ae4a66d8
Revises: c44fa72978d9
Create Date: 2026-08-12 19:39:08.799902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d8ae4a66d8'
down_revision: Union[str, None] = 'c44fa72978d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_song_scene', sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('is_song_scene')

    # ### end Alembic commands ###
